# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: beman_module.py tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  beman-module-script-ci:
    name: beman_module.py ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install pytest
        run: |
          python3 -m pip install pytest

      - name: Run pytest
        run: |
          cd beman_module
          pytest
